# Generated by Django 4.2.1 on 2023-08-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preciseweb', '0003_remove_getstarted_address_remove_getstarted_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='files'),
        ),
    ]
